#Lancer :   docker compose up -d
# Arrêter :  docker compose down        (les données persistent dans le volume)
# Reset :    docker compose down -v     (supprime le volume → le dump est rechargé au prochain up)
services:
  db:
    image: postgres:16
    container_name: laRemise-db

    environment:
      POSTGRES_USER: Admin
      POSTGRES_PASSWORD: Admin
      POSTGRES_DB: LaRemise
    volumes:
      - ./migration-up.sql:/docker-entrypoint-initdb.d/migration-up.sql
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data: